### ISSUE TITLE
Compiler run failed:

### ISSUE THREAD

**Issue by hadv** [uniswapfoundation/v4-template#52]
run 
```
$ forge test
```

```
Warning: This is a nightly build of Foundry. It is recommended to use the latest stable version. Visit https://book.getfoundry.sh/announcements for more information.
To mute this warning set `FOUNDRY_DISABLE_NIGHTLY_WARNING` in your environment.

Compiler run failed:
Error (6275): Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found. Searched the following locations: "/Users/hadv/points-hook".
ParserError: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found. Searched the following locations: "/Users/hadv/points-hook".
 --> lib/v4-periphery/src/interfaces/external/IWETH9.sol:4:1:
  |
4 | import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Compilation failed
```

**Comment by hadv** [comment]
by the way, it worked with `forge 0.3.0`

**Comment by saucepoint** [comment]
@hadv thanks for flagging -- were expecting users of the template to be on foundry stable; i'm unable to reproduce it on foundry stable, so seems to me foundry nightly is doing some new things with remappings?

will add it to the readme about using foundry stable

**Comment by saucepoint** [comment]
https://github.com/uniswapfoundation/v4-template/commit/c639c9b7079aed684979ab24d9140c87fb109010

will close for now, but feel free to reopen if the error persists

**Comment by hadv** [comment]
> [@hadv](https://github.com/hadv) thanks for flagging -- were expecting users of the template to be on foundry stable; i'm unable to reproduce it on foundry stable, so seems to me foundry nightly is doing some new things with remappings?
> 
> will add it to the readme about using foundry stable

okay, I didn't intend to use the nightly version; but it suddenly upgrade to that version after running `foundryup`
